export const GET_COMMUNITY_POSTS_REQUEST = 'GET_COMMUNITY_POSTS_REQUEST'
export const GET_COMMUNITY_POSTS_SUCCESS = 'GET_COMMUNITY_POSTS_SUCCESS'
export const GET_COMMUNITY_POSTS_FAILURE = 'GET_COMMUNITY_POSTS_FAILURE'

export const CREATE_COMMUNITY_POSTS_REQUEST = 'CREATE_COMMUNITY_POSTS_REQUEST'
export const CREATE_COMMUNITY_POSTS_SUCCESS = 'CREATE_COMMUNITY_POSTS_SUCCESS'
export const CREATE_COMMUNITY_POSTS_FAILURE = 'CREATE_COMMUNITY_POSTS_FAILURE'