export const GET_COMMUNITY_POST_REQUEST = 'GET_COMMUNITY_POST_REQUEST'
export const GET_COMMUNITY_POST_SUCCESS = 'GET_COMMUNITY_POST_SUCCESS'
export const GET_COMMUNITY_POST_FAILURE = 'GET_COMMUNITY_POST_FAILURE'

export const CREATE_COMMUNITY_POST_REQUEST = 'CREATE_COMMUNITY_POST_REQUEST'
export const CREATE_COMMUNITY_POST_SUCCESS = 'CREATE_COMMUNITY_POST_SUCCESS'
export const CREATE_COMMUNITY_POST_FAILURE = 'CREATE_COMMUNITY_POST_FAILURE'

export const DELETE_COMMUNITY_POST_REQUEST = 'DELETE_COMMUNITY_POST_REQUEST'
export const DELETE_COMMUNITY_POST_SUCCESS = 'DELETE_COMMUNITY_POST_SUCCESS'
export const DELETE_COMMUNITY_POST_FAILURE = 'DELETE_COMMUNITY_POST_FAILURE'