export const GET_DEBATE_POST_REQUEST = 'GET_DEBATE_POST_REQUEST'
export const GET_DEBATE_POST_SUCCESS = 'GET_DEBATE_POST_SUCCESS'
export const GET_DEBATE_POST_FAILURE = 'GET_DEBATE_POST_FAILURE'

export const CREATE_DEBATE_POST_REQUEST = 'CREATE_DEBATE_POST_REQUEST'
export const CREATE_DEBATE_POST_SUCCESS = 'CREATE_DEBATE_POST_SUCCESS'
export const CREATE_DEBATE_POST_FAILURE = 'CREATE_DEBATE_POST_FAILURE'

export const DELETE_DEBATE_POST_REQUEST = 'DELETE_DEBATE_POST_REQUEST'
export const DELETE_DEBATE_POST_SUCCESS = 'DELETE_DEBATE_POST_SUCCESS'
export const DELETE_DEBATE_POST_FAILURE = 'DELETE_DEBATE_POST_FAILURE'

export const UPDATE_DEBATE_POST_REQUEST = 'UPDATE_DEBATE_POST_REQUEST'
export const UPDATE_DEBATE_POST_SUCCESS = 'UPDATE_DEBATE_POST_SUCCESS'
export const UPDATE_DEBATE_POST_FAILURE = 'UPDATE_DEBATE_POST_FAILURE'